### ISSUE TITLE
Aula 3 a escolha da stack - Front-end web do app | NLW#1 Booster #2

### ISSUE THREAD

**Issue by DanielObara** [DanielObara/NLW-1.0#4]
### Intro :recycle:
- [x] Limpando a estrutura
- [x] Explicando conceitos
- [x] index.html e div root
- [x] JSX
- [x] Components
- [x] Props
- [x] State e imutabilidade

### Hands on
- [x] Files download
- [x] Html primeira pag
- [x] navegação
- [x] html form
- [x] mapa
- [x] busca itens
- [x] busca uf and city
- [x] cadastra ponto de coleta na api

**Comment by Bryanjames19** [comment]
Como eu faço pra acessar?

**Comment by DanielObara** [comment]
> Como eu faço pra acessar?

Olá @Bryanjames19 tudo bem? Essa aplicação não foi feita o deploy. Porém para acessar você pode rodar localmente.
Para rodar localmente, você precisa instalar todas as dependencias e rodar os scripts de inicialização da aplicação.

Para mais informações acesse o arquivo [readme.md ](https://github.com/DanielObara/NLW-1.0/blob/master/README.md)

Vlw!

**Comment by Bryanjames19** [comment]
Obg cara, me ajudou mt

Em seg, 26 de out de 2020 16:25, Daniel Obara <notifications@github.com>
escreveu:
